
api_key = '2HnmgAWGh2pBvEEnhaDXwYanyc4FJRbjwV2VlPrXD9XeW7xWx1voT8T3wzoVK1On'
api_secret = 'iHi4UbGOYRO0gxK6kYzjCojnJRUXdNqfIZaZn8Pu978IbEAR6F5krMMZYVR5Jon1'


SYMBOL = "BTC/USD"
POSITION_SIZE = 0.0001

# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 2

CHECK_ORDERS_FREQUENCY = 1
CLOSED_ORDER_STATUS = 'closed'
